/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PingRouteImport } from './routes/ping'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as privateIndexRouteImport } from './routes/(private)/index'
import { Route as privateProfileRouteImport } from './routes/(private)/profile'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'

const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateProfileRoute = privateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => privateRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/ping': typeof PingRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof privateProfileRoute
  '/': typeof privateIndexRoute
}
export interface FileRoutesByTo {
  '/ping': typeof PingRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof privateProfileRoute
  '/': typeof privateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(private)': typeof privateRouteRouteWithChildren
  '/ping': typeof PingRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(private)/profile': typeof privateProfileRoute
  '/(private)/': typeof privateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/ping' | '/signin' | '/signup' | '/profile' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/ping' | '/signin' | '/signup' | '/profile' | '/'
  id:
    | '__root__'
    | '/(auth)'
    | '/(private)'
    | '/ping'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(private)/profile'
    | '/(private)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  privateRouteRoute: typeof privateRouteRouteWithChildren
  PingRoute: typeof PingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ping': {
      id: '/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/profile': {
      id: '/(private)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof privateProfileRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface privateRouteRouteChildren {
  privateProfileRoute: typeof privateProfileRoute
  privateIndexRoute: typeof privateIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateProfileRoute: privateProfileRoute,
  privateIndexRoute: privateIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  PingRoute: PingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
